### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by pharno** [Jonatino/Java-Memory-Manipulation#1]
Hey, I just tried to build your project with maven, but it seems like its missing files.

[jmm.txt](https://github.com/Jonatino/Java-Memory-Manipulation/files/178019/jmm.txt)

**Comment by Jonatino** [comment]
Can you please try again, I've committed all the remaining files. 

Thanks for reporting it though!

**Comment by JavaVirtualMachine** [comment]
Hey is it possible to have Java docs comments so I know what each methods or var's do. Also If u have a guide on how to make cheats with java would be much appreciated. Apologies if ask to much or annoy you.
